### ISSUE TITLE
Allow S3 region to be set in config.json

### ISSUE THREAD

**Issue by pdkn** [AdobeDocs/photoshop-api-docs-pre-release#15]
### Expected Behaviour
Make it easy to configure S3 region (for `/jwt-sample-app` example)

### Actual Behaviour
S3 region is defaulted to `us-east-1` with no obvious way to set, if S3 bucket is in a different region the error returned `"unable to download input href"` is not obvious as to what is wrong.

### Reproduce Scenario (including but not limited to)
S3 buckets not in region `us-east-1` 

#### Steps to Reproduce
Create a S3 bucket in region `eu-west-1` 
Follow instructions
Then run -
Error at ```writeStatus(`  rendition: ${renditionResult.outputs[0]._links.renditions[0].href}`)```

**Comment by pdkn** [comment]
Pull request here - https://github.com/AdobeDocs/photoshop-api-docs-pre-release/pull/16

**Comment by pdkn** [comment]
The actual error message from AWS (if you paste the presigned input href into browser)
```
<Error>
<script/>
<Code>AuthorizationQueryParametersError</Code>
<Message>
Error parsing the X-Amz-Credential parameter; the region 'us-east-1' is wrong; expecting 'eu-west-1'
</Message>
<Region>eu-west-1</Region>
<RequestId>XXXX</RequestId>
<HostId>XXXX</HostId>
</Error>
```
which would be great to surface somehow in the `error.details` results of an api call to help with debugging

**Comment by noahhoffman** [comment]
@pdkn Thanks for contributing!  I'll pull this in today to both the pre-release and release sites.  I actually already have an open bug on my plate for this week or next to surface storage errors to the client like you've suggested
