### ISSUE TITLE
Example 4: /smartObject (Replacing smartobject) should there be a .psb example?

### ISSUE THREAD

**Issue by pdkn** [AdobeDocs/photoshop-api-docs-pre-release#18]
### Expected Behaviour
Linked .psb smartObject files should work with `//image.adobe.io/pie/psdService/smartObject`

### Actual Behaviour
Example Documentation only reference .psd. It would be beneficial to show or explain an example using .psb file

### Reproduce Scenario (including but not limited to)
.psd with linked .psb files

#### Steps to Reproduce
NA

#### Platform and Version
All

#### Sample Code that illustrates the problem
NA

#### Logs taken while reproducing problem
NA

**Comment by johnleetran** [comment]
Is this a bug in the service or is this a request to give more examples on PSB files?  The service should accept the psb, if not, let us know.

**Comment by pdkn** [comment]
This is a "Feature Request" in the documentation ;) However I am struggling to get a SO to update with an image. Doing more investigation identify the issue.

**Comment by khound** [comment]
@pdkn Our API supports replacing smart object with a `.psb` file. And also we have an example in the docs.
https://github.com/AdobeDocs/photoshop-api-docs-pre-release#example-4-smartobject-replacing-smartobject
The example shows a `jpeg` file. But ,our API doc mentions about the supported file type
https://adobedocs.github.io/photoshop-api-docs-pre-release/#api-Photoshop-smartObject

Your feedback will help us to improve. Please let us know, what was the issue? Is it finding file type in the docs? If so, how would you like to see it?
Thanks

**Comment by pdkn** [comment]
Thanks @khound. I’m not seeing any mention on .psb files in docs? The file types listed are . 
png
jpeg
psd
svg
ai
pdf

?

**Comment by khound** [comment]
@pdkn Actually all `.psb` are of file type `vnd.adobe.photoshop`, which is of same type as `psd`.  Since `.psb` are just larger `psd` files, we didn't mention in the supported type separately. But we can do that, anytime if it creates confusion. I am updating the API docs to add `.psb` to supported file type.

**Comment by pdkn** [comment]
Personally, I think it would help mentioning somewhere. But you call ;)
