### ISSUE TITLE
Bug - Psds with root Artboard unable to swap images in SmartObjects

### ISSUE THREAD

**Issue by pdkn** [AdobeDocs/photoshop-api-docs-pre-release#23]
### Expected Behaviour
A psd with SmartObjects nesting in Artboards should be update-able via `documentOperations`

### Actual Behaviour
A `documentOperations` that attempts to update a SmartObject with a new image has no effect (no errors are reported)

### Reproduce Scenario (including but not limited to)
A psd with SmartObjects nesting in an Artboard. (S3 external storage). i.e take [Example.psd](https://github.com/AdobeDocs/photoshop-api-docs-pre-release/blob/master/sample_files/Example.psd) and add a root Artboard labeled `300x600` with all layers contained within.

#### Steps to Reproduce
call a `documentOperations` to update SO with a [new image](https://github.com/AdobeDocs/photoshop-api-docs-pre-release/blob/master/sample_files/heroImage.png) (on S3 external storage), output to a png. Note the image has not been updated.
(**_This process has been testing with the Example.psd without Artboard and image updated correctly_**)

#### Platform and Version
All

#### Sample Code that illustrates the problem
```
{
	"blendOptions": {
		"blendMode": "normal",
		"opacity": 100
	},
	"bounds": {
		"height": 600,
		"left": 0,
		"top": 0,
		"width": 300
	},
	"children": [{
                 "blendOptions": {
			"blendMode": "normal",
			"opacity": 100
		},
		"bounds": {
			"height": 600,
			"left": 0,
			"top": 0,
			"width": 300
		},
		"id": 750,
		"index": 2,
		"locked": false,
		"name": "HeroImage",
		"smartObject": {
			"linked": false,
			"name": "Layer 19.psb",
			"type": "image/tiff"
		},
		"type": "smartObject",
		"visible": true,
		"edit": {},
		"input": {
			"href": "https://YOUR-BUCKET.s3.eu-west-1.amazonaws.com/heroImage.png?PRESIGNED_AUTH",
			"storage": "external"
		}
	}],
	"id": 784,
	"index": 10,
	"locked": false,
	"name": "300x600",
	"type": "layerSection",
	"visible": true
}
```
#### Logs taken while reproducing problem
Call https://image.adobe.io/pie/psdService/documentOperations API
jobId: 89a1819f-0982-4d92-ab1e-c99591b95b69

**Comment by johnleetran** [comment]
Thanks for reporting, i was able to reproduce the issue.  I have created internal issue with the team.  As a work around you can actually replace a smartObject layer by name (requirement for this is that all of your layer names are unique)
```
curl -H "Authorization: Bearer $TOKEN" -H "x-api-key: $API_KEY" https://image.adobe.io/pie/psdService/documentOperations -X POST -d '{
  "inputs": [
    {
      "href": "https://YOUR-BUCKET.s3.eu-west-1.amazonaws.com/template.psd?PRESIGNED_AUTH",
      "storage": "external"
    }
  ],
  "options": {
    "layers": [
      {
        "name": "HeroImage",
        "type": "smartObject",
        "visible": true,
        "edit": {},
        "input": {
          "href": "https://YOUR-BUCKET.s3.eu-west-1.amazonaws.com/heroImage.png?PRESIGNED_AUTH",
          "storage": "external"
        }
      }
    ]
  },
  "outputs": [
    {
      "storage": "external",
      "type": "image/jpg",
      "overwrite": true,
      "width": 0,
      "quality": 7,
      "href": "https://YOUR-BUCKET.s3.eu-west-1.amazonaws.com/output.jpg?PRESIGNED_AUTH"
    }
  ]
}'
```

**Comment by pdkn** [comment]
Thanks @johnleetran . Is there indefinite layer recursion to find the layer to edit? At the moment I'm doing multiple layer edits in one call (of images, text & shape fill colors) so basically sending the whole manifest back with marked layers to edit. Some layers to edit are a few (2 to 3) layerGroups down. Are you saying I can flatten the layers array sent to `documentOperations` and it will auto find them (as long as they are uniquely named)?

**Comment by johnleetran** [comment]
correct, if not, let us know

**Comment by pdkn** [comment]
Great, a few Array.map()/filter()'s later and got it working. One thing to note is the Example.psd in sample_files is using unsupported Adobe fonts so `documentOperations` with text edits will fail for `jwt service token` users at present.

**Comment by khound** [comment]
@pdkn We have put a fix for your original issue. You may like to test it.
