### ISSUE TITLE
Can't get OAuth Token

### ISSUE THREAD

**Issue by jbschrades** [AdobeDocs/photoshop-api-docs-pre-release#53]
### Expected Behaviour
Enter Client ID and Client Secret into https://ps-prerelease-us-east-1.cloud.adobe.io/ and get Token per instructions

### Actual Behaviour
Receive a 302 and nothing happens

**Comment by shayanc1985** [comment]
Hi @jbschrades, Do you have a JWT integration? If so, you will need to follow these instructions to get a token: https://github.com/AdobeDocs/photoshop-api-docs-pre-release#free-trial-users-jwt-authentication
