### ISSUE TITLE
Bad API key

### ISSUE THREAD

**Issue by Vico1993** [AdobeDocs/photoshop-api-docs-pre-release#6]
Hello!

Got admit to `Photoshop API Private Beta`. So I received my API Key and my client secret. 

I went on this website to get my bearer token https://ps-prerelease-us-east-1.cloud.adobe.io/

But Each time I'm making a call to `https://image.adobe.io/sensei/cutout` I received a 403 error:

`
{
    "error_code": "403003",
    "message": "Api Key is invalid"
}
`

Is it because the private BETA doesn't get access to `sensei/cutout` API?

My POST request looks like this:

`
Headers:
{
       "Content-Type": "application/json"
       "Authorization": "Bearer " + MY_TOKEN,
        "X-Api-Key": MY_API_KEY
}
`

**Comment by johnleetran** [comment]
Hello @Vico1993 

Thanks for reporting this.  We are aware of the issue and we'll update the ticket once we resolve the issue.  

Best
John Tran

**Comment by Vico1993** [comment]
Thank you John 👍

**Comment by jessefulton** [comment]
I'm also having this issue - is there workaround we could use until this is resolved?

**Comment by johnleetran** [comment]
Hello @jessefulton, we will be happy to help.  May i ask you to send a request to psdservices@adobe.com?  We can fix the issue if we know which API key we allocated to you.

Best
John Tran
